#ifndef _RELATION_H_
#define _RELATION_H_

RELATION_BEGIN(User)
    RELATION_HAS(Town,          4  )
    RELATION_HAS(Resource,      4  )
    RELATION_HAS(Army,          4  )
    RELATION_HAS(Item,          256)
RELATION_END(User)

#endif


#!/bin/bash

#######################################################################################
#generate table_relation.h
#######################################################################################
out='table_relation.h'
cat << EOF > $out 
/*
 *Warning!!!!!
 *This file is generated by script file ---- expand_relations.sh
 *Do not modify!
*/

#include "table_pub.h"

EOF
     
cat relations.h | awk 'BEGIN { FS = "[,\(\)]"; table_no = 0 } { print $1, $2, $3, $4, $5 }' | awk '
    {
        if($1 == "RELATION_BEGIN") {
            print "/* relation descriptions of table @"$2" */"
            print "TF tf_"$2"[] = {"
        }  
        if($1 == "RELATION_END") {
            print "};/* End @"$2" */"
            print "const int tfn_"$2" = sizeof(tf_"$2")/sizeof(TF);"
            printf "TI ti_"$2" = {TNO_"toupper($2)",\t sizeof("$2"),\t tf_"$2",\t TFN_"toupper($2)",\t \""tolower($2)"s\",\t \""$2"\"};\n\n\n"
        }
        if($1 == "RELATION_HAS") {
            printf "\t{\"%-15s ,\t       sizeof(%-7s),\t %5d,\t sizeof(%-7s),\t FT_%-7s, },\n", $3"\"",     $2,  1, $2, $2 
        }
        if($1 == "FIELD_A") {
            printf "\t{\"%-15s ,\t %3d * sizeof(%-7s),\t %5d,\t sizeof(%-7s),\t FT_%-7s, },\n", $3"\"", $4, $2, $4, $2, $2 
        }
    }' >> $out
    
