#!/bin/bash

#######################################################################################
#generate table_fields.c
#######################################################################################
out='table_fields.c'
cat << EOF > $out
/*
 *Warning!!!!!
 *This file is generated by script file ---- table_expand.sh
 *Do not modify!
*/

#include "table_def.h"
#include "table_fields.h"

EOF

cat tables.h | awk 'BEGIN { FS = "[,\(\)]" } { print $1, $2, $3, $4, $5 }' | awk '
	{
		if($1 == "TABLE_BEGIN") {
			print "/* Field descriptions of table @"$2" */"
      		print "TF tf_"$2"[] = {"
      	}  
   		if($1 == "TABLE_END") {
     		print "};/* End @"$2" */\n"
     		print "const int tfn_"$2" = sizeof(tf_"$2")/sizeof(TF);\n"
     	}
     	if($1 == "FIELD") {
     		print "\t{\""$2"\",\t \""$3"\",\t sizeof("$2"),\t 1,\t sizeof("$2"),\t },"
     	}
     	if($1 == "FIELD_A") {
     		print "\t{\""$2"\",\t \""$3"\",\t sizeof("$2")*"$4",\t "$4",\t sizeof("$2"),\t },"
     	}
 	}' >> $out
 	

#######################################################################################
#generate table_fields.h
#######################################################################################
out='table_fields.h'
cat << EOF > $out
/*
 *Warning!!!!!
 *This file is generated by script file ---- table_expand.sh
 *Do not modify!
*/

#include "table_def.h"

EOF

cat tables.h | awk 'BEGIN { FS = "[,\(\)]" } { print $1, $2, $3, $4, $5 }' | awk '
	{
		if($1 == "TABLE_BEGIN") {
			print "/* Field descriptions of table @"$2" */"
      		print "extern TF tf_"$2"[];"
      		print "extern const int tfn_"$2";\n\n"
      	}  
 	}' >> $out
