/*
 *Warning!!!!!
 *This file is generated by script file ---- table_expand.sh
 *Do not modify!
*/

#include "table_def.h"
#include "table_fields.h"

/* Field descriptions of table @User */
TF tf_User[] = {
	{"UINT32",	 "id",	 sizeof(UINT32),	 1,	 sizeof(UINT32),	 },
	{"UINT8",	 "level",	 sizeof(UINT8),	 1,	 sizeof(UINT8),	 },
	{"UINT8",	 "vip",	 sizeof(UINT8),	 1,	 sizeof(UINT8),	 },
	{"UINT16",	 "exp",	 sizeof(UINT16),	 1,	 sizeof(UINT16),	 },
	{"CHAR",	 "name",	 sizeof(CHAR)*32,	 32,	 sizeof(CHAR),	 },
	{"CHAR*",	 "extra",	 sizeof(CHAR*),	 1,	 sizeof(CHAR*),	 },
	{"DOUBLE",	 "pay",	 sizeof(DOUBLE),	 1,	 sizeof(DOUBLE),	 },
};/* End @User */

const int tfn_User = sizeof(tf_User)/sizeof(TF);

/* Field descriptions of table @Server */
TF tf_Server[] = {
	{"UINT32",	 "id",	 sizeof(UINT32),	 1,	 sizeof(UINT32),	 },
	{"CHAR",	 "name",	 sizeof(CHAR)*32,	 32,	 sizeof(CHAR),	 },
	{"CHAR",	 "identifier",	 sizeof(CHAR)*32,	 32,	 sizeof(CHAR),	 },
	{"CHAR",	 "category",	 sizeof(CHAR)*16,	 16,	 sizeof(CHAR),	 },
};/* End @Server */

const int tfn_Server = sizeof(tf_Server)/sizeof(TF);

