/*
 *Warning!!!!!
 *This file is generated by script file ---- table_expand.sh
 *Do not modify!
*/

#include "table_def.h"

/* Field descriptions of table @User */
extern TF tf_User[];
extern const int tfn_User;


/* Field descriptions of table @Server */
extern TF tf_Server[];
extern const int tfn_Server;


