/*
 *Warning!!!!!
 *This file is generated by script file ---- table_expand.sh
 *Do not modify!
*/

#include "table_pub.h"

/* Field descriptions of table @User */
TF tf_User[] = {
	{"id"             ,	       sizeof(UINT32 ),	     1,	 sizeof(UINT32 ),	 FT_UINT32 , },
	{"level"          ,	       sizeof(UINT8  ),	     1,	 sizeof(UINT8  ),	 FT_UINT8  , },
	{"vip"            ,	       sizeof(UINT8  ),	     1,	 sizeof(UINT8  ),	 FT_UINT8  , },
	{"exp"            ,	       sizeof(UINT16 ),	     1,	 sizeof(UINT16 ),	 FT_UINT16 , },
	{"name"           ,	  32 * sizeof(NCHAR  ),	    32,	 sizeof(NCHAR  ),	 FT_NCHAR  , },
	{"extra"          ,	       sizeof(STRING ),	     1,	 sizeof(STRING ),	 FT_STRING , },
	{"pay"            ,	       sizeof(DOUBLE ),	     1,	 sizeof(DOUBLE ),	 FT_DOUBLE , },
};/* End @User */
const int tfn_User = sizeof(tf_User)/sizeof(TF);
TI ti_User = {TNO_USER,	 sizeof(User),	 tf_User,	 TFN_USER,	 "users",	 "User"};


/* Field descriptions of table @Server */
TF tf_Server[] = {
	{"id"             ,	       sizeof(UINT32 ),	     1,	 sizeof(UINT32 ),	 FT_UINT32 , },
	{"name"           ,	  32 * sizeof(NCHAR  ),	    32,	 sizeof(NCHAR  ),	 FT_NCHAR  , },
	{"identifier"     ,	  32 * sizeof(NCHAR  ),	    32,	 sizeof(NCHAR  ),	 FT_NCHAR  , },
	{"category"       ,	  16 * sizeof(NCHAR  ),	    16,	 sizeof(NCHAR  ),	 FT_NCHAR  , },
};/* End @Server */
const int tfn_Server = sizeof(tf_Server)/sizeof(TF);
TI ti_Server = {TNO_SERVER,	 sizeof(Server),	 tf_Server,	 TFN_SERVER,	 "servers",	 "Server"};


