#ifndef _TABLE_INFO_H
#define _TABLE_INFO_H
/*
 *Warning!!!!!
 *This file is generated by script file ---- table_expand.sh
 *Do not modify!
*/

/* Field descriptions of table @User 		*/
#define TNO_USER	1
#define TNO_User	1		/* alternative 	*/
#define TFN_USER		 ( sizeof(tf_User)/sizeof(TF) )
extern  TF tf_User[];
extern  const int tfn_User;
extern  TI ti_User;


/* Field descriptions of table @Server 		*/
#define TNO_SERVER	2
#define TNO_Server	2		/* alternative 	*/
#define TFN_SERVER		 ( sizeof(tf_Server)/sizeof(TF) )
extern  TF tf_Server[];
extern  const int tfn_Server;
extern  TI ti_Server;


#define TNO_MINIMUM	 1 

#define TNO_MAXIMUM	 2

#endif
