/*
*Warning!!!!!
*This file is generated by script file ---- expand_tables.sh
*Do not modify!
*/

#include "table_pub.h"

/* Field descriptions of table @User */
TF tf_User[] = {
    {"id"             ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"level"          ,        sizeof(UINT8  ),      1,  sizeof(UINT8  ),    FT_UINT8  , },
    {"vip"            ,        sizeof(UINT8  ),      1,  sizeof(UINT8  ),    FT_UINT8  , },
    {"exp"            ,        sizeof(UINT16 ),      1,  sizeof(UINT16 ),    FT_UINT16 , },
    {"name"           ,   32 * sizeof(NCHAR  ),     32,  sizeof(NCHAR  ),    FT_NCHAR  , },
    {"extra"          ,        sizeof(STRING ),      1,  sizeof(STRING ),    FT_STRING , },
    {"pay"            ,        sizeof(DOUBLE ),      1,  sizeof(DOUBLE ),    FT_DOUBLE , },
};/* End @User */
const int tfn_User = sizeof(tf_User)/sizeof(TF);
TI ti_User = {TNO_USER,  sizeof(User),   tf_User,    TFN_USER,   "users",    "User",     "user_id"};


/* Field descriptions of table @Server */
TF tf_Server[] = {
    {"id"             ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"name"           ,   32 * sizeof(NCHAR  ),     32,  sizeof(NCHAR  ),    FT_NCHAR  , },
    {"identifier"     ,   32 * sizeof(NCHAR  ),     32,  sizeof(NCHAR  ),    FT_NCHAR  , },
    {"category"       ,   16 * sizeof(NCHAR  ),     16,  sizeof(NCHAR  ),    FT_NCHAR  , },
};/* End @Server */
const int tfn_Server = sizeof(tf_Server)/sizeof(TF);
TI ti_Server = {TNO_SERVER,  sizeof(Server),     tf_Server,  TFN_SERVER,     "servers",  "Server",   "server_id"};


/* Field descriptions of table @Town */
TF tf_Town[] = {
    {"id"             ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"user_id"        ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"zone"           ,        sizeof(UINT16 ),      1,  sizeof(UINT16 ),    FT_UINT16 , },
    {"position"       ,        sizeof(UINT16 ),      1,  sizeof(UINT16 ),    FT_UINT16 , },
    {"level"          ,        sizeof(UINT16 ),      1,  sizeof(UINT16 ),    FT_UINT16 , },
    {"flags"          ,        sizeof(UINT16 ),      1,  sizeof(UINT16 ),    FT_UINT16 , },
    {"name"           ,   32 * sizeof(NCHAR  ),     32,  sizeof(NCHAR  ),    FT_NCHAR  , },
    {"type"           ,   16 * sizeof(NCHAR  ),     16,  sizeof(NCHAR  ),    FT_NCHAR  , },
    {"category"       ,   16 * sizeof(NCHAR  ),     16,  sizeof(NCHAR  ),    FT_NCHAR  , },
};/* End @Town */
const int tfn_Town = sizeof(tf_Town)/sizeof(TF);
TI ti_Town = {TNO_TOWN,  sizeof(Town),   tf_Town,    TFN_TOWN,   "towns",    "Town",     "town_id"};


/* Field descriptions of table @Resource */
TF tf_Resource[] = {
    {"id"             ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"user_id"        ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"town_id"        ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"gold"           ,        sizeof(UINT64 ),      1,  sizeof(UINT64 ),    FT_UINT64 , },
    {"food"           ,        sizeof(UINT64 ),      1,  sizeof(UINT64 ),    FT_UINT64 , },
    {"wood"           ,        sizeof(UINT64 ),      1,  sizeof(UINT64 ),    FT_UINT64 , },
    {"stone"          ,        sizeof(UINT64 ),      1,  sizeof(UINT64 ),    FT_UINT64 , },
};/* End @Resource */
const int tfn_Resource = sizeof(tf_Resource)/sizeof(TF);
TI ti_Resource = {TNO_RESOURCE,  sizeof(Resource),   tf_Resource,    TFN_RESOURCE,   "resources",    "Resource",     "resource_id"};


/* Field descriptions of table @Army */
TF tf_Army[] = {
    {"id"             ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"user_id"        ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"town_id"        ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"army_1"         ,        sizeof(UINT64 ),      1,  sizeof(UINT64 ),    FT_UINT64 , },
    {"army_2"         ,        sizeof(UINT64 ),      1,  sizeof(UINT64 ),    FT_UINT64 , },
    {"army_3"         ,        sizeof(UINT64 ),      1,  sizeof(UINT64 ),    FT_UINT64 , },
};/* End @Army */
const int tfn_Army = sizeof(tf_Army)/sizeof(TF);
TI ti_Army = {TNO_ARMY,  sizeof(Army),   tf_Army,    TFN_ARMY,   "armys",    "Army",     "army_id"};


/* Field descriptions of table @Item */
TF tf_Item[] = {
    {"id"             ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"user_id"        ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"amount"         ,        sizeof(UINT32 ),      1,  sizeof(UINT32 ),    FT_UINT32 , },
    {"name"           ,   32 * sizeof(NCHAR  ),     32,  sizeof(NCHAR  ),    FT_NCHAR  , },
};/* End @Item */
const int tfn_Item = sizeof(tf_Item)/sizeof(TF);
TI ti_Item = {TNO_ITEM,  sizeof(Item),   tf_Item,    TFN_ITEM,   "items",    "Item",     "item_id"};


